In [31]:
import torch

a = torch.tensor([1, 2, 3.], requires_grad=True)
print(a.grad)

None


In [32]:
out = a.sigmoid()
out

tensor([0.7311, 0.8808, 0.9526], grad_fn=<SigmoidBackward>)

In [33]:
c = out.detach()
print(c)

tensor([0.7311, 0.8808, 0.9526])


In [34]:
out.sum().backward()
print(c.requires_grad)
print(out.requires_grad)

print(a.grad)

False
True
tensor([0.1966, 0.1050, 0.0452])
